export const LOAD_USER = "LOAD_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED"
export const USER_LOAD_ERROR = "USER_LOAD_ERROR"
export const USER_REGISTER = "USER_REGISTER"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR"