# Generated by Django 3.1.7 on 2021-03-16 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='user',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
