# Generated by Django 3.1.7 on 2021-03-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210316_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='userId',
            new_name='user_id',
        ),
    ]
